### ISSUE TITLE
Ignores root= parameter

### ISSUE THREAD

**Issue by rajil** [fernando-rodriguez/ssmtp-reloaded#3]
Hello,

Both ssmtp and ssmtp-reloaded are ignoring the root= parameter on my machine. The log for ssmtp-2.64-r2 is posted at https://forums.gentoo.org/viewtopic-t-1034122.html

Any idea what is the issue?

**Comment by fdev1** [comment]
Try using ssmtp directly instead of trough the mail utility:

`echo -e 'Subject: Test\nThis is a test' | ssmtp root`

It should work, meaning that the problem is that the mail utility appends the system hostname. However, it may be a valid bug as we can match the full username (including hostname), so I will look into it.

**Comment by rajil** [comment]
Thanks. With directly invoking ssmtp it works as expected. 

To work around this bug i removed net-mail/mailutils and installed mail-client/mailx

**Comment by fdev1** [comment]
Fixed in version 0.9.5
